full_data_path: path/to/data/wildchat.json  # {/databricks-dolly-15k_alpaca_style.json, /alpaca_davinci_data.json, /alpaca_gpt4_data.json, }
model_name_or_path: path/to/model/8b-base  # path to pretrained foundation llm
cache_dir: ~
model_max_length: 4096
val_set_size: 0  
evol_schedule_name: KCenterSampling # {KCenterSampling, LeastConfidence, MarginSampling, EntropySampling, RandomSampling, }
result_dir_name: llama3_8B_wildchat_10w # name for the folder storing all results -> we suggest including keywords of the evol_schedule, e.g., "kc_{dataset}_{other_params}"
train_args:
  optim: adamw_torch
  num_train_epochs: 3
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 16
  evaluation_strategy: "no"
  save_strategy: "steps"
  save_steps: 2000
  save_total_limit: 1
  learning_rate: 7.0e-6
  weight_decay: 0.1
  warmup_ratio: 0.01
  lr_scheduler_type: cosine
  logging_steps: 1
  ddp_timeout: 180000000
  fsdp: "full_shard auto_wrap" 
  fsdp_transformer_layer_cls_to_wrap: LlamaDecoderLayer
  bf16: TRUE
  tf32: FALSE
init_label_num: 1000 
n_round: 3 
n_query: 3000
